# Autogenerated wrapper script for igraph_jll for aarch64-apple-darwin
export libigraph

using Arpack_jll
using GLPK_jll
using GMP_jll
using libblastrampoline_jll
using XML2_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("igraph")
JLLWrappers.@declare_library_product(libigraph, "@rpath/libigraph.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Arpack_jll, GLPK_jll, GMP_jll, libblastrampoline_jll, XML2_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libigraph,
        "lib/libigraph.3.1.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
