# Autogenerated wrapper script for igraph_jll for i686-w64-mingw32-cxx03
export libigraph

using Arpack_jll
using GLPK_jll
using GMP_jll
using libblastrampoline_jll
using XML2_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("igraph")
JLLWrappers.@declare_library_product(libigraph, "libigraph.dll")
function __init__()
    JLLWrappers.@generate_init_header(Arpack_jll, GLPK_jll, GMP_jll, libblastrampoline_jll, XML2_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libigraph,
        "bin\\libigraph.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
